Added option to either display the field on lower case or as it was defined
chop-dbhi/cilantro pull request #790
Opened 2017-10-02 18:00 UTC by rennomarcus

Context:
We had a request to change one the modules behavior: vocab. 
Vocab has a component, called bucket and within this component the name of the field that was selected is displayed. The thing is that one the fields contains a name, Fyler, thus it should not be lower cased. 

Solution:
I added an option to let the field not be lower cased.

2017-11-09 21:05 UTC, rennomarcus commented
Hi, @bruth . I made this small change. I was hoping you could review and share your thoughts about this change. 

Thanks!

2017-11-09 21:21 UTC, bruth commented
A more general solution could be to provide a function in the config that takes the names as an argument and then call that in the component if defined.

```js
{
  // ..

  fieldNameDisplay: function(names) {
    return {
      single: names.single.toLowerCase(),
      plural: names.plural.toLowerCase()
    }
  },
}
```

2017-11-16 16:45 UTC, rennomarcus commented
Thanks reviewing it! I agree with what you said and I think it's better.
I changed the code and I hope it's closer to what you said.
Now one can change the function to execute whatever they want with certain names.
Example:
```
fieldNameDisplay: function fieldNameDisplay(names) {
    if (names.single.toLowerCase() !== 'fyler diagnosis') {
        return {
          single: names.single.toLowerCase() || '',
          plural: names.plural.toLowerCase() || ''
        };
    }
    return names;
}
```

2017-11-16 18:01 UTC, bruth requested changes

2017-11-16 18:01 UTC, bruth commented on src/js/cilantro/config.js
> +         *  - displayFieldLowerCase: format that the field name will be displayed
Update comment to reflect name change.

2017-11-16 18:01 UTC, bruth commented on src/js/cilantro/config.js
> +            fieldNameDisplay: function fieldNameDisplay(names) {
Was using a *named* function here intentional for debugging purposes? (As supposed to an anonymous function `function(names) { ... }`.

2017-11-28 18:54 UTC, rennomarcus commented
Hi, @bruth. I've updated the comments and removed the function name to maintain the consistency. Let me know if you have any other comments. Thanks!

2023-01-26 14:39 UTC, closed without merging